# Form implementation generated from reading ui file 'prueba.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from pathlib import Path
import scipy.io.wavfile as wav
import matplotlib.pyplot as plt
import numpy as np
from pydub import AudioSegment


def comprimir():
    # ====== CARGAR AUDIO ======
    carpeta_principal = Path('Recursos')
    nombre_archivo = 'In_Piano.wav'
    ruta_archivo = carpeta_principal / nombre_archivo

    if ruta_archivo.exists():
        frecuencia_muestreo, datos_audio = wav.read(ruta_archivo)
        if len(datos_audio.shape) > 1:
            datos_audio = np.mean(datos_audio, axis=1)  # Promediar los dos canales
            datos_audio = np.int16(datos_audio)  # Convertir a enteros

        # ====== TRANSFORMADA DE FOURIER ======
        transformada = np.fft.fft(datos_audio)
        frecuencias = np.fft.fftfreq(len(transformada), d=1/frecuencia_muestreo)

        # ====== FILTRADO DE PASO BAJO ======
        frecuencia_corte = 10000  # 10 kHz
        transformada_filtrada = np.where(np.abs(frecuencias) > frecuencia_corte, 0, transformada)

        # ====== TRANSFORMADA INVERSA ======
        datos_filtrados = np.fft.ifft(transformada_filtrada).real
        datos_filtrados = np.int16(datos_filtrados)

        # ====== GUARDAR COMO WAV TEMPORAL ======
        nombre_archivo_temporal = 'Audio_Temporal.wav'
        wav.write(nombre_archivo_temporal, frecuencia_muestreo, datos_filtrados)

        # ====== CONVERTIR A MP3 ======
        nombre_archivo_mp3 = 'Audio_Reducido.mp3'
        ruta_salida_mp3 = carpeta_principal / nombre_archivo_mp3
        audio = AudioSegment.from_wav(nombre_archivo_temporal)
        audio.export(ruta_salida_mp3, format="mp3", bitrate="128k")
        print(f'Archivo guardado en formato MP3 en: {ruta_salida_mp3}')

    else:
        print("El archivo no existe en la ruta especificada.")





class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(360, 110, 91, 31))
        self.textEdit.setObjectName("textEdit")
        self.button_compirmir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_compirmir.setGeometry(QtCore.QRect(350, 190, 111, 31))
        self.button_compirmir.setObjectName("button_compirmir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.button_compirmir.clicked.connect(comprimir)
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PRUEBA</p></body></html>"))
        self.button_compirmir.setText(_translate("MainWindow", "COMPRIMIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
